### PR TITLE
Refactor the code of conduct :)

### PR DESCRIPTION
**Pull request by spudowiar**
**MAJOR** refactor, possibly do not merge.

### CODE REVIEW

**Comment by vktec** [comment]
Seems good so far, but how about clarifying the "Please do not" section, by restating not to at the beginning of each bullet (eg. " - Don't advertise..." or " - Please don't advertise...")

**Comment by vktec** [comment]
Looks good, I'll merge to `devel`

**Comment by spudowiar** [comment]
Grrr `git pull-request` made a PR against `master` :/

**Comment by vktec** [comment]
No problem, `devel` is currently level with `master` anyway

**Comment by vktec** [comment]
Okay, I've merged this to `devel`. Thanks for your input @spudowiar!

**Comment by spudowiar** [comment]
No problem :)

**Pull request closed without merging**
